# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.16.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import giteaclient
from giteaclient.models.repository_meta import RepositoryMeta  # noqa: E501
from giteaclient.rest import ApiException


class TestRepositoryMeta(unittest.TestCase):
    """RepositoryMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRepositoryMeta(self):
        """Test RepositoryMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteaclient.models.repository_meta.RepositoryMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
