# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.16.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import giteaclient
from giteaclient.models.time_stamp import TimeStamp  # noqa: E501
from giteaclient.rest import ApiException


class TestTimeStamp(unittest.TestCase):
    """TimeStamp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeStamp(self):
        """Test TimeStamp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteaclient.models.time_stamp.TimeStamp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
