# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.16.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import giteaclient
from giteaclient.models.external_wiki import ExternalWiki  # noqa: E501
from giteaclient.rest import ApiException


class TestExternalWiki(unittest.TestCase):
    """ExternalWiki unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalWiki(self):
        """Test ExternalWiki"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteaclient.models.external_wiki.ExternalWiki()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
