# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.16.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import giteaclient
from giteaclient.models.general_api_settings import GeneralAPISettings  # noqa: E501
from giteaclient.rest import ApiException


class TestGeneralAPISettings(unittest.TestCase):
    """GeneralAPISettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneralAPISettings(self):
        """Test GeneralAPISettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteaclient.models.general_api_settings.GeneralAPISettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
