# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.16.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import giteaclient
from giteaclient.models.id_assets_body import IdAssetsBody  # noqa: E501
from giteaclient.rest import ApiException


class TestIdAssetsBody(unittest.TestCase):
    """IdAssetsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdAssetsBody(self):
        """Test IdAssetsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteaclient.models.id_assets_body.IdAssetsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
