# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.16.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import giteaclient
from giteaclient.models.commit_status_state import CommitStatusState  # noqa: E501
from giteaclient.rest import ApiException


class TestCommitStatusState(unittest.TestCase):
    """CommitStatusState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCommitStatusState(self):
        """Test CommitStatusState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteaclient.models.commit_status_state.CommitStatusState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
