# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.16.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import giteaclient
from giteaclient.models.delete_file_options import DeleteFileOptions  # noqa: E501
from giteaclient.rest import ApiException


class TestDeleteFileOptions(unittest.TestCase):
    """DeleteFileOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteFileOptions(self):
        """Test DeleteFileOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteaclient.models.delete_file_options.DeleteFileOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
