# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.16.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import giteaclient
from giteaclient.models.combined_status import CombinedStatus  # noqa: E501
from giteaclient.rest import ApiException


class TestCombinedStatus(unittest.TestCase):
    """CombinedStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCombinedStatus(self):
        """Test CombinedStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteaclient.models.combined_status.CombinedStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
