# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.16.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import giteaclient
from giteaclient.models.add_collaborator_option import AddCollaboratorOption  # noqa: E501
from giteaclient.rest import ApiException


class TestAddCollaboratorOption(unittest.TestCase):
    """AddCollaboratorOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddCollaboratorOption(self):
        """Test AddCollaboratorOption"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteaclient.models.add_collaborator_option.AddCollaboratorOption()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
